### ISSUE TITLE
How to add video files from Desktop app?

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/kenzie.design#3]
Hi @thomasjbradley 😸 

I was wondering if there's an easier way to add video files to repositories than uploading them manually through the Github website? 

When I create folders containing mp4 files locally, neither Atom nor the Github Desktop app see the mp4 files, so my regular method of creating commits doesn't push those files.

Do you have any thoughts?

**Comment by MacKenzieRose** [comment]
Thanks for getting back to me 😸 

Do you think several small video files would cause problems, if the total of the video files is larger than 2MB?

Historically, how did people with motion portfolios accommodate that? Linking to external video hosting platforms?

**Comment by MacKenzieRose** [comment]
^^Fantastic. I will avoid video content for the time being, and try not to lock anything 🙂 

Unrelated, but I've been looking a little into site analytics, including Google Analytics, Data Studio, and Google Search Console. Do you normally embed things like that into your sites for clients? Are there better/other tools I should look at using? Or are they something to avoid altogether?

**Comment by thomasjbradley** [comment]
I don’t put analytics on too many sites anymore because I found none of my clients actually ever looked at them. So I was sacrificing speed and privacy for something they never used. I have one client that wanted basic analytics so we just used the ones built into WordPress & that was enough.

There’s a lot of concern with Google Analytics in privacy circles because of how well they can track users across properties. There are a bunch of alternatives that are more privacy focused. The major benefit of GA is that it’s free.

Here are a few alternatives:
- https://www.goatcounter.com/
- https://posthog.com/
- https://www.usertrack.net/
- https://plausible.io/
- https://simpleanalytics.com/

**Comment by MacKenzieRose** [comment]
You're a star 🌟 Thank you!
